### ISSUE TITLE
 大佬，运行报错，这个是什么问题？

### ISSUE THREAD

**Issue by waiwa5** [CyrusRenty/MOOC-Download#4]
Traceback (most recent call last):
  File "main.py", line 160, in get_content
    sources).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 239, in <module>
    main()
  File "main.py", line 235, in main
    get_course_all_source(course.course_id)
  File "main.py", line 108, in get_course_all_source
    video_level)
  File "main.py", line 167, in get_content
    sources).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Riumin** [comment]
我也是这个问题 同求

**Comment by iamwilliamli** [comment]
一样
